### ISSUE TITLE
Crash when generating with latest installed Chrome (109.0.5414.75)

### ISSUE THREAD

**Issue by MarkIngramUK** [BaristaLabs/chrome-dev-tools#28]
**Chrome:** 109.0.5414.75
**chrome-dev-tools-generator:** `abdf32b`

`GetProtocolDefinitionData` crashes in `new PdlConverter(pdlScript);` when executing the script: `Engine.Execute(script, Scope);`.

```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'CodecsInfo' threw an exception.
  Source=IronPython
  StackTrace:
   at IronPython.Runtime.Operations.StringOps.TryGetEncoding(String name, Encoding& encoding)
   at IronPython.Compiler.Tokenizer.TryGetEncoding(Encoding defaultEncoding, String line, Encoding& enc, String& encName)
   at IronPython.Runtime.PythonContext.GetSourceReader(Stream stream, Encoding defaultEncoding, String path)
   at Microsoft.Scripting.Runtime.LanguageBoundTextContentProvider.GetReader()
   at IronPython.Compiler.Parser.CreateParserWorker(CompilerContext context, PythonOptions options, Boolean verbatim)
   at IronPython.Runtime.PythonContext.ParseAndBindAst(CompilerContext context)
   at IronPython.Runtime.PythonContext.CompilePythonCode(SourceUnit sourceUnit, CompilerOptions options, ErrorSink errorSink)
   at IronPython.Runtime.PythonContext.CompileModule(String fileName, String moduleName, SourceUnit sourceCode, ModuleOptions options, ScriptCode& scriptCode)
   at IronPython.Runtime.Importer.LoadModuleFromSource(CodeContext context, String name, String path)
   at IronPython.Runtime.Importer.LoadFromDisk(CodeContext context, String name, String fullName, String str)
   at IronPython.Runtime.Importer.ImportFromPathHook(CodeContext context, String name, String fullName, List path, Func`5 defaultLoader)
   at IronPython.Runtime.Importer.ImportFromPath(CodeContext context, String name, String fullName, List path)
   at IronPython.Runtime.Importer.ImportTopAbsolute(CodeContext context, String name)
   at IronPython.Runtime.Importer.ImportModule(CodeContext context, Object globals, String modName, Boolean bottom, Int32 level)
   at IronPython.Modules.Builtin.__import__(CodeContext context, String name, Object globals, Object locals, Object fromlist, Int32 level)
   at Microsoft.Scripting.Interpreter.FuncCallInstruction`7.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run7[T0,T1,T2,T3,T4,T5,T6,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
   at IronPython.Runtime.Importer.ImportLightThrow(CodeContext context, String fullName, PythonTuple from, Int32 level)
   at IronPython.Runtime.Operations.PythonOps.ImportBottom(CodeContext context, String fullName, Int32 level)
   at Microsoft.Scripting.Interpreter.FuncCallInstruction`4.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run1[T0,TRet](T0 arg0)
   at IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
   at IronPython.Runtime.PythonContext.InitializeModule(String fileName, ModuleContext moduleContext, ScriptCode scriptCode, ModuleOptions options)
   at IronPython.Runtime.Importer.LoadModuleFromSource(CodeContext context, String name, String path)
   at IronPython.Runtime.Importer.LoadFromDisk(CodeContext context, String name, String fullName, String str)
   at IronPython.Runtime.Importer.ImportFromPathHook(CodeContext context, String name, String fullName, List path, Func`5 defaultLoader)
   at IronPython.Runtime.Importer.ImportFromPath(CodeContext context, String name, String fullName, List path)
   at IronPython.Runtime.Importer.ImportTopAbsolute(CodeContext context, String name)
   at IronPython.Runtime.Importer.ImportModule(CodeContext context, Object globals, String modName, Boolean bottom, Int32 level)
   at IronPython.Modules.Builtin.__import__(CodeContext context, String name, Object globals, Object locals, Object fromlist, Int32 level)
   at Microsoft.Scripting.Interpreter.FuncCallInstruction`7.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run7[T0,T1,T2,T3,T4,T5,T6,TRet](T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
   at IronPython.Runtime.Importer.ImportLightThrow(CodeContext context, String fullName, PythonTuple from, Int32 level)
   at Microsoft.Scripting.Interpreter.FuncCallInstruction`4.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
   at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at ChromeDevToolsGeneratorCLI.PdlConverter..ctor(String script) in C:\Users\me\Code\chrome-dev-tools\src\ChromeDevToolsGeneratorCLI\PdlConverter.cs:line 31
   at ChromeDevToolsGeneratorCLI.Program.<GetProtocolDefinitionData>d__1.MoveNext() in C:\Users\me\Code\chrome-dev-tools\src\ChromeDevToolsGeneratorCLI\Program.cs:line 113
   at ChromeDevToolsGeneratorCLI.Program.Main(String[] args) in C:\Users\me\Code\chrome-dev-tools\src\ChromeDevToolsGeneratorCLI\Program.cs:line 37

  This exception was originally thrown at this call stack:
    System.Text.Encoding.GetDataItem()
    System.Text.Encoding.WindowsCodePage.get()
    IronPython.Runtime.Operations.StringOps.CodecsInfo.MakeCodecsDict()
    IronPython.Runtime.Operations.StringOps.CodecsInfo.CodecsInfo()

Inner Exception 1:
NotSupportedException: No data is available for encoding 932. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
```

**Comment by jdpurcell** [comment]
I was getting this error too, but it went away after I updated the IronPython NuGet packages.
